scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['127.0.0.1:9090']

  - job_name: 'envoy'
    metrics_path: '/stats'
    params:
      format: ['prometheus']
    scrape_interval: 5s
    static_configs:
      - targets: ['lb:9901']

  - job_name: 'java-services'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: [ 'app:8080' ]
        labels:
          application: event-sourcing-account